name: storygen
channels:
  - pytorch
  - defaults
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.10.11=h06a4308_0
  - certifi=2022.12.7=py38h06a4308_0
  - cffi=1.15.1=py38h74dc2b5_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cryptography=37.0.1=py38h9ce1e76_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9e=h7f8727e_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libdeflate=1.8=h7f8727e_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.4.0=hecacb30_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.19.2=py38h4c65ebe_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1s=h7f8727e_0
  - pillow=9.2.0=py38hace64e9_1
  - pip=20.3.3=py38h06a4308_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.5=h7579374_1
  - pytorch=1.12.1=py3.8_cuda11.3_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py38h06a4308_0
  - setuptools=63.4.1=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.39.3=h5082296_0
  - tk=8.6.12=h1ccaba5_0
  - torchvision=0.13.1=py38_cu113
  - typing_extensions=4.3.0=py38h06a4308_0
  - urllib3=1.26.11=py38h06a4308_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.6=h5eee18b_0
  - zlib=1.2.12=h5eee18b_3
  - zstd=1.5.2=ha4553b6_0
  - pip:
    - absl-py==1.2.0
    - accelerate==0.17.1
    - aiofiles==23.1.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - altair==4.2.2
    - antlr4-python3-runtime==4.9.3
    - anyio==3.6.2
    - appdirs==1.4.4
    - asttokens==2.2.1
    - async-timeout==4.0.2
    - attrs==22.1.0
    - av==10.0.0
    - backcall==0.2.0
    - bitsandbytes==0.36.0.post2
    - black==21.4b2
    - blessed==1.19.1
    - cachetools==5.2.0
    - click==8.1.3
    - cloudpickle==2.2.0
    - comm==0.1.3
    - contourpy==1.0.5
    - cupy-cuda11x==11.6.0
    - cycler==0.11.0
    - datasets==2.6.1
    - debugpy==1.6.7
    - decorator==4.4.2
    - detectron2==0.6+cu111
    - diffusers==0.13.1
    - dill==0.3.5.1
    - easydict==1.10
    - einops==0.5.0
    - einops-exts==0.0.3
    - entrypoints==0.4
    - executing==1.2.0
    - fairscale==0.4.13
    - fastapi==0.95.0
    - fastrlock==0.8.1
    - ffmpy==0.3.0
    - filelock==3.8.0
    - fonttools==4.38.0
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - ftfy==6.1.1
    - future==0.18.2
    - fvcore==0.1.5.post20220512
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - gpustat==1.0.0
    - gradio==3.23.0
    - grpcio==1.49.1
    - h11==0.14.0
    - httpcore==0.16.3
    - httpx==0.23.3
    - huggingface-hub==0.14.1
    - hydra-core==1.2.0
    - image-reward==1.2
    - imageio==2.22.1
    - imageio-ffmpeg==0.4.8
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - iopath==0.1.9
    - ipykernel==6.23.0
    - ipython==8.12.2
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - jsonschema==4.17.3
    - jupyter-client==8.2.0
    - jupyter-core==5.3.0
    - kiwisolver==1.4.4
    - kornia==0.6.7
    - linkify-it-py==2.0.0
    - logger==1.4
    - loguru==0.7.0
    - lpips==0.1.4
    - markdown==3.4.1
    - markdown-it-py==2.2.0
    - markupsafe==2.1.1
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mdit-py-plugins==0.3.3
    - mdurl==0.1.2
    - modelcards==0.1.6
    - moviepy==1.0.3
    - multidict==6.0.2
    - multiprocess==0.70.13
    - mypy-extensions==0.4.3
    - nest-asyncio==1.5.6
    - networkx==2.8.7
    - numpy==1.24.2
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-ml-py==11.495.46
    - nvitop==1.1.2
    - oauthlib==3.2.1
    - omegaconf==2.2.3
    - openai==0.27.2
    - opencv-python==4.6.0.66
    - orjson==3.8.8
    - packaging==21.3
    - pandas==1.5.1
    - parso==0.8.3
    - pathspec==0.10.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pkgutil-resolve-name==1.3.10
    - platformdirs==3.5.1
    - portalocker==2.6.0
    - prettytable==3.6.0
    - proglog==0.1.10
    - prompt-toolkit==3.0.38
    - protobuf==3.19.6
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyarrow==9.0.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycocotools==2.0.5
    - pydantic==1.10.6
    - pydeprecate==0.3.2
    - pydot==1.4.2
    - pydub==0.25.1
    - pyecharts==2.0.1
    - pygments==2.15.1
    - pyparsing==3.0.9
    - pyre-extensions==0.0.23
    - pyrsistent==0.19.3
    - python-dateutil==2.8.2
    - python-multipart==0.0.6
    - pytorch-fid==0.3.0
    - pytorch-lightning==1.7.7
    - pytorch-metric-learning==2.1.1
    - pytz==2022.5
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==25.0.2
    - regex==2022.9.13
    - requests-oauthlib==1.3.1
    - responses==0.18.0
    - rfc3986==1.5.0
    - rotary-embedding-torch==0.1.5
    - rsa==4.9
    - scikit-image==0.19.3
    - scikit-learn==1.2.2
    - scipy==1.9.2
    - seaborn==0.12.2
    - semantic-version==2.10.0
    - simplejson==3.18.3
    - sniffio==1.3.0
    - stack-data==0.6.2
    - starlette==0.26.1
    - tabulate==0.9.0
    - tenacity==8.2.2
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorboardx==2.5.1
    - termcolor==2.0.1
    - thop==0.1.1-2209072238
    - threadpoolctl==3.1.0
    - tifffile==2022.8.12
    - timm==0.6.13
    - tokenizers==0.13.1
    - toml==0.10.2
    - toolz==0.12.0
    - torch==1.13.1
    - torchaudio==0.13.1+cu116
    - torchmetrics==0.10.0
    - torchstat==0.0.7
    - tornado==6.3.1
    - tqdm==4.64.1
    - traitlets==5.9.0
    - transformers==4.27.4
    - triton==1.1.1
    - typing-inspect==0.8.0
    - uc-micro-py==1.0.1
    - uvicorn==0.21.1
    - video-diffusion-pytorch==0.6.0
    - wcwidth==0.2.5
    - websockets==10.4
    - werkzeug==2.2.2
    - xformers==0.0.13
    - xxhash==3.1.0
    - yacs==0.1.8
    - yarl==1.8.1
    - youtube-dl==2021.12.17
    - zipp==3.9.0
